// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptDatabase(arg1:string,arg2:string):Promise<string>;

export function GetCurrentConfig():Promise<Record<string, any>>;

export function GetWeChatKey():Promise<string>;

export function SaveBasicConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function SaveFeishuConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveFilesConfig(arg1:string,arg2:string):Promise<string>;

export function SaveSyncConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartHTTPServer(arg1:string):Promise<string>;

export function SyncToFeishu(arg1:string,arg2:string):Promise<string>;

export function TestFeishuConfig(arg1:string,arg2:string):Promise<string>;

export function TestHTTPServer(arg1:string):Promise<string>;

export function TestSyncConfig(arg1:string,arg2:string):Promise<string>;
