// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptDatabase(arg1, arg2) {
  return window['go']['main']['App']['DecryptDatabase'](arg1, arg2);
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetWeChatKey() {
  return window['go']['main']['App']['GetWeChatKey']();
}

export function SaveBasicConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveBasicConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveFeishuConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFeishuConfig'](arg1, arg2, arg3);
}

export function SaveFilesConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveFilesConfig'](arg1, arg2);
}

export function SaveSyncConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSyncConfig'](arg1, arg2, arg3);
}

export function StartHTTPServer(arg1) {
  return window['go']['main']['App']['StartHTTPServer'](arg1);
}

export function SyncToFeishu(arg1, arg2) {
  return window['go']['main']['App']['SyncToFeishu'](arg1, arg2);
}

export function TestFeishuConfig(arg1, arg2) {
  return window['go']['main']['App']['TestFeishuConfig'](arg1, arg2);
}

export function TestHTTPServer(arg1) {
  return window['go']['main']['App']['TestHTTPServer'](arg1);
}

export function TestSyncConfig(arg1, arg2) {
  return window['go']['main']['App']['TestSyncConfig'](arg1, arg2);
}
